WebAppToDoList/Models/ErrorViewModel.cs
using System;

namespace WebAppToDoList.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppToDoList/Models/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppToDoList.Models
{
    public class IndexViewModel
    {
        public TodoModel form { get; set; }
        public List<TodoModel> listaTodos { get; set; } = new List<TodoModel>();
    }
}

WebAppToDoList/Models/ResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppToDoList.Models
{
    public class ResponseModel
    {
        public TodoModel Value { get; set; }
        public IEnumerable<string> Formatters { get; set; }
        public IEnumerable<string> ContentTypes { get; set; }
        public IEnumerable<string> DeclaredType { get; set; }
        public int StatusCode { get; set; }
    }
}

WebAppToDoList/Models/ResponseModelList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppToDoList.Models
{
    public class ResponseModelList
    {
        public IList<TodoModel> Value { get; set; }
        public IEnumerable<string> Formatters { get; set; }
        public IEnumerable<string> ContentTypes { get; set; }
        public IEnumerable<string> DeclaredType { get; set; }
        public int StatusCode { get; set; }
    }
}

WebAppToDoList/Models/TodoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppToDoList.Models
{
    public class TodoModel
    {
        public Guid Id { get; set; }
        [Required]
        public string Responsavel { get; set; }
        [Required]
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        [Required]
        public string Estado { get; set; }
    }
}

WebAppToDoList/Controllers/ToDosController.cs
using Infra.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Threading.Tasks;
using WebAppToDoList.Models;

namespace WebAppToDoList.Controllers
{
    public class ToDosController : Controller
    {
        private string URL = "https://todoappfunctionsat.azurewebsites.net/api/";

        public async Task<IActionResult> Index()
        {
            HttpClient httpClient = new HttpClient();

            var request = await httpClient.GetAsync($"{URL}GetTodosToDo");
            var response = await request.Content.ReadAsStringAsync();
            ResponseModelList todos = JsonConvert.DeserializeObject<ResponseModelList>(response);

            foreach(var item in todos.Value)
            {
                switch (item.Estado)
                {
                    case "2":
                        item.Estado = "Fazendo";
                        break;
                    case "3":
                        item.Estado = "Feito";
                        break;
                    default:
                        item.Estado = "Backlog";
                        break;
                }
            }

            return View(todos.Value);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            HttpClient httpClient = new HttpClient();

            var request = await httpClient.GetAsync($"{URL}GetById?id={id}");
            var response = await request.Content.ReadAsStringAsync();
            ResponseModel todo = JsonConvert.DeserializeObject<ResponseModel>(response);

            switch (todo.Value.Estado)
            {
                case "2":
                    todo.Value.Estado = "Fazendo";
                    break;
                case "3":
                    todo.Value.Estado = "Feito";
                    break;
                default:
                    todo.Value.Estado = "Backlog";
                    break;
            }

            return View(todo.Value);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                HttpClient httpClient = new HttpClient();

                var todoItem = new itemRequest();
                todoItem.responsavel = collection["Responsavel"];
                todoItem.titulo = collection["Titulo"];
                todoItem.descricao = collection["Descricao"];
                todoItem.estado = collection["Estado"];

                var item = JsonConvert.SerializeObject(todoItem);

                var body = new StringContent(item, System.Text.Encoding.UTF8, "application/json");

                await httpClient.PostAsync($"{URL}CriaToDo", body);

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            HttpClient httpClient = new HttpClient();

            var request = await httpClient.GetAsync($"{URL}GetById?id={id}");
            var response = await request.Content.ReadAsStringAsync();
            ResponseModel todo = JsonConvert.DeserializeObject<ResponseModel>(response);

            return View(todo.Value);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                HttpClient httpClient = new HttpClient();

                var todoItem = new itemRequest();
                todoItem.responsavel = collection["Responsavel"];
                todoItem.titulo = collection["Titulo"];
                todoItem.descricao = collection["Descricao"];
                todoItem.estado = collection["Estado"];

                var item = JsonConvert.SerializeObject(todoItem);
                var body = new StringContent(item, System.Text.Encoding.UTF8, "application/json");
                await httpClient.PutAsync($"{URL}UpdateTodo?id={id}", body);

                return RedirectToAction("Index");
            } else
            {
                return RedirectToAction("Edit");
            }
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            HttpClient httpClient = new HttpClient();

            var request = await httpClient.GetAsync($"{URL}GetById?id={id}");
            var response = await request.Content.ReadAsStringAsync();
            ResponseModel todo = JsonConvert.DeserializeObject<ResponseModel>(response);

            switch (todo.Value.Estado)
            {
                case "2":
                    todo.Value.Estado = "Fazendo";
                    break;
                case "3":
                    todo.Value.Estado = "Feito";
                    break;
                default:
                    todo.Value.Estado = "Backlog";
                    break;
            }

            return View(todo.Value);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id, IFormCollection collection)
        {
            HttpClient httpClient = new HttpClient();

            await httpClient.DeleteAsync($"{URL}RemoveToDo?id={id}");

            return RedirectToAction("Index");
        }
    }
}

WebAppToDoList/Views/Home/Index.cshtml
@model WebAppToDoList.Models.IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="app-container d-flex align-items-center justify-content-center flex-column">        
    <h3>Todo App</h3>
    <div class="d-flex align-items-center mb-3">
        <form>
            <div class="form-group mr-3 mb-0">
                <input type="text"
                       class="form-control"
                       id="formGroupExampleInput"
                       placeholder="Enter a task here" />
            </div>
            <button type="button"
                    class="btn btn-primary mr-3">
                Save
            </button>
        </form>
    </div>

    <div class="table-wrapper">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>item</th>
                    <th>estado</th>
                    <th>responsavel</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td>
                        
                    </td>
                    <td></td>
                    <td>
                        <button class="btn btn-danger">
                            Delete
                        </button>
                        <button class="btn btn-success">
                            Finished
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

WebAppToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ToDos" asp-action="Index">To Do App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1"></ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAppToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppToDoList/Views/ToDos/Create.cshtml
@model WebAppToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Create";
}

<h4>Adicionar tarefa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group d-none">
                <label asp-for="Id" class="control-label d-none"></label>
                <input asp-for="Id" class="form-control d-none" />
            </div>
            <div class="form-group">
                <label asp-for="Responsavel" class="control-label"></label>
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger">É necessário que a tarefa tenha um responsável</span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger">É necessário que a tarefa tenha um titulo</span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="1">Backlog</option>
                    <option value="2">Fazendo</option>
                    <option value="3">Feito</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppToDoList/Views/ToDos/Delete.cshtml
@model WebAppToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Delete";
}

<h4>Deletar</h4>

<h5>Tem certeza que quer deletar?</h5>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2 d-none">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10 d-none">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Responsavel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Responsavel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-dark" asp-action="Index">Back to List</a>
    </form>
</div>

WebAppToDoList/Views/ToDos/Details.cshtml
@model WebAppToDoList.Models.TodoModel

@{
    ViewData["Title"] = "View";
}

<h4>Detalhes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label d-none"></label>
                <input asp-for="Id" class="form-control d-none" />
                <span asp-validation-for="Id" class="text-danger d-none"></span>
            </div>
            <div class="form-group">
                <label asp-for="Responsavel" class="control-label"></label>
                <input asp-for="Responsavel" class="form-control" readonly/>
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" readonly/>
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" readonly />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" readonly />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group d-none">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppToDoList/Views/ToDos/Edit.cshtml
@model WebAppToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Editar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group d-none">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Responsavel" class="control-label"></label>
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger">É necessário que a tarefa tenha um responsável</span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger">É necessário que a tarefa tenha um titulo</span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="1">Backlog</option>
                    <option value="2">Fazendo</option>
                    <option value="3">Feito</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppToDoList/Views/ToDos/Index.cshtml
@model IEnumerable<WebAppToDoList.Models.TodoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>A fazeres</h1>

<p>
    <a class="btn btn-success" asp-action="Create">Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th class="d-none">
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Responsavel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="d-none">
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Responsavel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>